name: C++ and Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install C++ dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ unzip

      - name: Download and Build Google Test
        run: |
          wget -O googletest-release-1.11.0.zip https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip
          unzip googletest-release-1.11.0.zip
          cd googletest-release-1.11.0
          mkdir build && cd build
          cmake ..
          make
          # Copy Google Test libraries to system path
          sudo cp googlemock/*.a /usr/lib
          sudo cp googletest/*.a /usr/lib

      - name: Configure and Build C++ Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run C++ Unit Tests
        run: |
          cd build
          ./tests/test_boundary
          ./tests/test_fdm
          ./tests/test_payoff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib

      - name: Run Python Visualization
        run: |
          python plot_option_pricing_surface.py

      - name: Save Plot as Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: option-pricing-plot
          path: plot.png
